services:
  api:
    build: .
    container_name: cnv_sandbox
    ports:
      - "8001:8001"
      - "8016:8016"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
