services:
  # sandbox_api:
  #   build: .
  #   container_name: cnv_sandbox_api
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - REDIS_HOST=redis
  #   depends_on:
  #     - redis
  #     - runner
  #   command:
  #     [
  #       "/app/sandbox/.venv/bin/uvicorn",
  #       "main:app",
  #       "--host",
  #       "0.0.0.0",
  #       "--port",
  #       "8001",
  #     ]
  #   volumes:
  #     - ./algorithms_container:/app/sandbox/algorithms_container

  redis:
    image: redis:latest
    container_name: cnv_sandbox_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
