services:
  mysql:
    image: mysql:latest
    container_name: cnv_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cnv_pgt_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.

  minio:
    image: minio/minio:latest
    container_name: cnv_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: miniorootpw
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    volumes:
      - minio_data:/data

volumes:
  minio_data:
